fastlane_version '2.157'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do
      run_tests(scheme: "CIBasicIntroduction",
      device: "iPhone 14")
    end
end